#!/usr/bin/env node
/**
 * Coverage Ratchet Script
 *
 * Ensures code coverage never decreases from the baseline.
 * Reads coverage from coverage/coverage-summary.json (generated by vitest --coverage)
 * Compares against .coverage/baseline.json
 *
 * Usage:
 *   pnpm run test:coverage:ratchet    # Check against baseline
 *   pnpm run test:coverage:update     # Update baseline to current
 */

const { readFileSync, writeFileSync, existsSync, mkdirSync } = require('node:fs');
const { dirname, join } = require('node:path');

const THRESHOLD = 0.01; // Allow 0.01% tolerance for floating point
function isCiMode() {
  return !!process.env.CI && process.env.CI !== '0' && process.env.CI.toLowerCase() !== 'false';
}

function getCoveragePath() {
  const baseDir = process.env.COVERAGE_RATCHET_CWD || process.cwd();
  return join(baseDir, 'coverage/coverage-summary.json');
}

function getBaselinePath() {
  const baseDir = process.env.COVERAGE_RATCHET_CWD || process.cwd();
  return join(baseDir, '.coverage/baseline.json');
}

function readCurrentCoverage() {
  const coveragePath = getCoveragePath();
  if (!existsSync(coveragePath)) {
    console.error(`❌ Coverage file not found: ${coveragePath}`);
    console.error('   Run "pnpm run test:coverage" first');
    process.exit(1);
  }

  const summary = JSON.parse(readFileSync(coveragePath, 'utf-8'));
  const total = summary.total;

  return {
    lines: total.lines.pct,
    functions: total.functions.pct,
    branches: total.branches.pct,
    statements: total.statements.pct,
  };
}

function readBaseline() {
  const baselinePath = getBaselinePath();
  if (!existsSync(baselinePath)) {
    return null;
  }
  const baseline = JSON.parse(readFileSync(baselinePath, 'utf-8'));
  return baseline.coverage;
}

function writeBaseline(coverage) {
  const baselinePath = getBaselinePath();
  const dir = dirname(baselinePath);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  const baseline = {
    version: '1.0.0',
    timestamp: new Date().toISOString(),
    coverage,
  };

  writeFileSync(baselinePath, JSON.stringify(baseline, null, 2) + '\n');
}

function formatCoverage(metrics) {
  return `lines: ${metrics.lines.toFixed(2)}%, ` +
    `functions: ${metrics.functions.toFixed(2)}%, ` +
    `branches: ${metrics.branches.toFixed(2)}%, ` +
    `statements: ${metrics.statements.toFixed(2)}%`;
}

function compareCoverage(current, baseline) {
  const failures = [];
  const metrics = ['lines', 'functions', 'branches', 'statements'];

  for (const metric of metrics) {
    const diff = current[metric] - baseline[metric];
    if (diff < -THRESHOLD) {
      failures.push(`${metric}: ${baseline[metric].toFixed(2)}% → ${current[metric].toFixed(2)}% (${diff.toFixed(2)}%)`);
    }
  }

  return failures;
}

function main() {
  const args = process.argv.slice(2);
  const command = args[0] || 'check';

  if (command === 'update') {
    const current = readCurrentCoverage();
    writeBaseline(current);
    console.log('✅ Coverage baseline updated');
    console.log(`   ${formatCoverage(current)}`);
    process.exit(0);
  }

  // Check mode (default)
  const current = readCurrentCoverage();
  const baseline = readBaseline();

  if (!baseline) {
    if (isCiMode()) {
      console.error('❌ Coverage baseline missing in CI');
      console.error('   Create and commit baseline locally with:');
      console.error('   pnpm run test:coverage:update');
      process.exit(1);
    }

    console.log('⚠️  No baseline found. Creating initial baseline...');
    writeBaseline(current);
    console.log('✅ Baseline created');
    console.log(`   ${formatCoverage(current)}`);
    process.exit(0);
  }

  console.log('📊 Coverage Comparison');
  console.log(`   Current:  ${formatCoverage(current)}`);
  console.log(`   Baseline: ${formatCoverage(baseline)}`);

  const failures = compareCoverage(current, baseline);
  if (failures.length > 0) {
    console.error('\n❌ Coverage regression detected:');
    for (const failure of failures) {
      console.error(`   • ${failure}`);
    }
    console.error('\nTo update baseline (if intentional):');
    console.error('   pnpm run test:coverage:update');
    process.exit(1);
  }

  // Check if coverage improved.
  const improved = compareCoverage(baseline, current);
  if (improved.length > 0) {
    console.log('\n✅ Coverage improved above baseline');
    if (!isCiMode()) {
      console.log('   Baseline not auto-updated in check mode.');
      console.log('   To lock in gains, run: pnpm run test:coverage:update');
    }
  } else {
    console.log('\n✅ Coverage meets baseline');
  }

  process.exit(0);
}

module.exports = {
  main,
  readCurrentCoverage,
  readBaseline,
  writeBaseline,
  compareCoverage,
};

if (require.main === module) {
  main();
}
